name: DAST

on:
  pull_request:
    branches:
      - main

jobs:
  dast:
    name: OWASP ZAP BASELINE SCAN
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Building Docker Login Form Image
        run: docker build --tag login-form:latest .
      - name: Launching the Login Form app
        run: docker run -d -p 5000:5000 login-form

      - name: OWASP ZAP
        ### Swap the actions used if you want a more comprehensive DAST analysis of your app :)
        # uses: zaproxy/action-full-scan@v0.3.0
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: "http://localhost:5000"
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          fail_action: false
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: DAST Security Tests
          cmd_options: '-I'
